version: '3.8'

services:
  pixiv-proxy:
    image: ghcr.io/rorical/pixiv-image-proxy:latest
    ports:
      - "443:443"
    environment:
      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=443
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
      
      # Upstream Configuration
      - UPSTREAM_HOST=https://i.pximg.net
      - UPSTREAM_REFERER=https://www.pixiv.net/
      
      # S3 Storage Configuration
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      
      # Redis Configuration
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      
      # Cache TTL Configuration
      - CACHE_404_TTL=86400
      - CACHE_ERROR_TTL=1200
      
      # Logging
      - RUST_LOG=pixiv_image_proxy=info,tower_http=info
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - redis
      - minio
    restart: unless-stopped
    networks:
      - proxy-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - proxy-network
    restart: unless-stopped
  
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
    volumes:
      - minio-data:/data
    networks:
      - proxy-network
    restart: unless-stopped

volumes:
  redis-data:
  minio-data:

networks:
  proxy-network: